### ISSUE TITLE
Can't build from Master. 'C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by EmilyLove26** [WillHayCode/Deadname-Remover#259]
I tried to build from master but ran into the following error. Shame the chrome extension in the store is nearly 2 months old. Isn't it suppose to get updated once a month?
```
npm run production

> deadname-remover@1.1.2 production D:\Downloads\2\Deadname-Remover-master
> node tasks/build.js --production

(node:20064) UnhandledPromiseRejectionWarning: Error: tsc exited with error: Error: Command failed: C:\Program Files\nodejs\node.exe D:\Downloads\2\Deadname-Remover-master\node_modules\typescript\lib\tsc.js --project "tsconfig.json"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

    at D:\Downloads\2\Deadname-Remover-master\tasks\type-checking.js:7:24
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Gusted** [comment]
> Shame the chrome extension in the store is nearly 2 months old.

#227

**Comment by EmilyLove26** [comment]
Ah so that's what's up.

**Comment by Gusted** [comment]
Hi @EmilyLove26

Thanks for letting me know about the issue, personally only tested with Linux. Which rarely use spaces in folders.
I've fixed it for now and you can pull the latest commit to build it again.

Regards,
Gusted

**Comment by EmilyLove26** [comment]
Thanks for the reference. I'll fix it manually so I can build it.

**Comment by EmilyLove26** [comment]
Built successfully on Windows 10
